### ISSUE TITLE
Need to modify resource-workspace-rcl to support callback on layout changes

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/resource-workspace-rcl#10]
We need to modify resource-workspace-rcl to support callback on layout changes.  Specifically the ResponsiveGridLayout does support a layout change callback named onLayoutChange(). We just need to add support into resource-workspace-rcl.

DoD:  The app remembers the layout changes after clicking the refresh button/logging out/clearing cache/new session in same browser.

**Comment by cckozie** [comment]
v0.2.0 build cbad9c9
The card layout is maintained through refreshing, logging out, clearing cache, and starting a new session in the same browser.

**Comment by elsylambert** [comment]
Works as expected in v0.9.0 build ab13659. The layout was maintained in all the defined cases.
