### ISSUE TITLE
SPIKE: Investigate workspace rcl

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/resource-workspace-rcl#2]

**Comment by birchamp** [comment]
mockup
https://projects.invisionapp.com/share/6VZ7U05QCMN#/screens/435786056

Notes:
https://docs.google.com/document/d/1dEYW59IGqiU2S94G7DJYdOiglIQzxqL00l_g2lLqC7c/edit#

**Comment by RoyalSix** [comment]
<img width="1017" alt="Screen Shot 2020-11-09 at 10 16 51 PM" src="https://user-images.githubusercontent.com/16184018/98635144-4a04ac80-22d9-11eb-8c0c-5af58cbbcaed.png">

**Comment by birchamp** [comment]
@RoyalSix add increments and dynamically create.  Test min 2/12 size

![Screenshot 2020-10-09 at 15.06.49.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/603fc3e8-8251-46e1-9425-4d20089840b8)

**Comment by RoyalSix** [comment]
https://5faeedb4e9c2eb3a7a19b0ca--reverent-lumiere-9de4a7.netlify.app/
